config/routes.rb
Rails.application.routes.draw do
  get 'teams/show'

  get 'dashborads/index'
  get 'invites/token_url'
  root 'dashborads#index'
	resources :accounts do 
		resources :teams
	end
  resources :invites 
  devise_for :users, controllers: {sessions: 'users/sessions' , registrations: 'users/registrations'}
end

app/models/account.rb
class Account < ActiveRecord::Base
	# belongs_to :user
	validates :name, presence: true
end

app/models/invite.rb
class Invite < ActiveRecord::Base
	before_create :generate_token
	before_save :check_user_existence

	def check_user_existence
		user = User.find_by_email(email)
		if user
		  self.user_id = user.id
		end
	end

	def generate_token
	   self.token = Digest::SHA1.hexdigest([self.accounts_id, Time.now, rand].join)
	end
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :accounts_name, :invite_token
  after_create :generate_user_or_invite_user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def generate_user_or_invite_user
    Account.create(name: accounts_name, owner_id: self.id) if accounts_name
	  if invite_token != nil
	     org =  Invite.find_by_token(invite_token)
	     org.update(user_id: self.id, token: "") if org
	  end
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def show
	  @account = Account.find(params[:id])
	  @users_in_account = Invite.where(account_id: @account.id)
	  @users = Array.new
	      @users_in_account.each do |u|
	        user_id = u.user_id
	        u = User.find_by(id: user_id)
	        @users.push(u)
	        end
	      @users
	      @teams = Team.where(account_id: @account.id) 
	end
	 

	private
	   def valid_params
	     params.require(:account).permit(:name, :owner_id)
	   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  before_action :configure_permitted_parameters, if: :devise_controller?
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :check_url, only: [:new], if: :devise_controller?

  # def create
  #   super
  # end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :accounts_name, :invite_token])
  end

  def check_url
    if params[:invite_token].present?
      org =  Invite.find_by_token(params[:invite_token]) #find the user group attached to the invite
      redirect_to(invites_token_url_path) unless org
    end
  end
end

app/controllers/dashborads_controller.rb
class DashboradsController < ApplicationController
	def index
		check_for_account = Account.find_by(owner_id: current_user.id)
		if check_for_account == nil
			@accounts = Array.new
			@invitations = Invite.where(owner_id: current_user.id)
			@invitations.each do |invite|
				acc_id = invite.accounts_id
				account = Account.find_by(id: acc_id)
				@accounts.push(account)
			end
		else
			@accounts = Account.where(owner_id: current_user.id)
		end
	end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
	before_action :authenticate_user!, :except => [:token_url]
	before_action :check_user_exist, only: :create

	def new
		@invite =  Invite.new
		@account = Account.where(owner_id: current_user.id).first
	end


	def create
	  @invite = Invite.new(invite_params)
	  if @invite.save
	    #if the user already exists
	    if @invite.user_id != nil 
	       InviteMailer.existing_user_invite(@invite, new_user_session_path).deliver_now
	    else
	       InviteMailer.new_user_invite(@invite, new_user_registration_path(:invite_token => @invite.token)).deliver_now
	    end
	  else
	     redirect_to(new_invite_path)
	  end
	  redirect_to root_path 
	end

	def token_url
	end

	private

	def check_user_exist
		present= Invite.where(accounts_id: params[:invite][:accounts_id], email: params[:invite][:email], token: "").first
		redirect_to(new_invite_path) if present
	end

	def invite_params
		params.require(:invite).permit!
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def member_or_owner(user_id)
		check = Account.find_by(owner_id: user_id)
		check == nil ? "Member" : "Owner" 
	end
	
end

app/helpers/dashborads_helper.rb
module DashboradsHelper
end

app/helpers/invite_helper.rb
module InviteHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/accounts/show.html.erb
<%if member_or_owner(current_user.id) == "Owner"%>
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="row">

                <a id="modal-366601" href="#modal-container-366601" role="button" class="btn btn-primary float-left" data-toggle="modal">Add Users</a></br>
                <a id="modal-3666010" href="#modal-container-3666010" role="button" class="btn btn-primary float-right" data-toggle="modal">Add Teams</a>
                <div class="modal fade" id="modal-container-366601" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">Invite Users for <%= @account.name%></h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>

                            <div class="modal-body">
                                <%= form_for :invite, :url => invites_path, :method => :post do |form| %>
                                    <div class="form-control">
                                        <%= form.label :email %>
                                            <br/>
                                            <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
                                                <%= form.hidden_field :accounts_id , :value => @account.id %>
                                    </div>
                                    <div class="modal-footer">
                                        <%= form.submit "Invite" %>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                                Close
                                            </button>
                                    </div>
                                    <%end%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-container-3666010" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Create teams <%= @account.name%></h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>

                <div class="modal-body">
                    <%= form_for :team , url: account_teams_path(account_id: params[:id]) do |form|%>
                        <div class="form-control">
                            <%= form.label :Team_name %>
                                <br/>
                                <%= form.text_field :Team_name,class:"form-control", autofocus: true, autocomplete: "email" %>
                        </div>
                        <div class="modal-footer">
                            <%= form.submit "Create",class: "btn btn-success" %>

                        </div>
                        <%end%>
                </div>
            </div>
        </div>
    </div>

    <% end %>

        <h3 class="row d-flex justify-content-center mt-3"><%= @account.name.capitalize%> Dashboard</h3>
        <script src="https://drvic10k.github.io/bootstrap-sortable/Scripts/bootstrap-sortable.js"></script>
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-md-10">
                <table class="table table-hover sortable border bg-light">
                    <thead class="thead-light">
                        <tr class="d-flex">
                            <th class="col-2">
                                Sr.no<i class="fa fa-fw fa-sort"></i>
                            </th>
                            <th class="col-2">
                                NAME <i class="fa fa-fw fa-sort"></i>
                            </th>
                            <th class="col-4">
                                Email <i class="fa fa-fw fa-sort"></i>
                            </th>
                            <th class="col-2">
                                Status <i class="fa fa-fw fa-sort"></i>
                            </th>
                            <th class="col-2">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% count =0 %>
                            <% @users.each do |user| %>
                                <tr class="d-flex">
                                    <td class="col-2">
                                        <%= count+=1 %>
                                    </td>
                                    <td class="col-2">
                                        <%= user.name %>
                                    </td>
                                    <td class="col-4">
                                        <%= user.email%>
                                    </td>
                                    <td class="col-2">
                                        <%=member_or_owner(user.id)%>
                                    </td>
                                    <td class="col-2">
                                    </td>
                                </tr>
                                <% end %>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4 mt-4 ml-4">
                <% @teams.each do |u| %>
                    <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                        <div class="card-header">Team</div>
                        <div class="card-body">
                            <a href="<%= accounts_team_path(@account,u)%>">
                                <h5 class="card-title"><%= u.Team_name%></h5></a>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        </div>
                    </div>
                <% end %>
            </div>
        <div>

app/views/dashborads/index.html.erb
<div class="card bg-light mt-3 ml-3" style="max-width: 20rem;">
  <div class="card-header">Accounts</div>
    <div class="card-body">
      <p class="card-text">
        <% @accounts.each do |account|%>
          <a href="<%= account_path(account) %>">
          <h4><%= account.name %></h4>
          </a>
          <p>owner: (<%=current_user.email%>)</p>
        <%end%>
      </p>
    </div>
</div>

app/views/invites/new.html.erb
<%= form_for @invite , :url => invites_path do |f| %>
    <%= f.hidden_field :accounts_id, :value => @account.id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send' %>
<% end %>

app/views/invites/toekn_url.html.erb
<p>This is a dead link and given url is not valid</p>

app/views/invites/token_url.html.erb
<p>This is a dead link and given url is not valid</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mpm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <b>Maropost</b>
  </a>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button"></button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path%>">
          Home
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-md-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown">
            <%= current_user.name %>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="<%= edit_user_registration_path %>">Edit Profile</a>
            <%= link_to 'Signout', destroy_user_session_path, method: "delete", class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
          <%= link_to'Sign-up', new_user_registration_path, class: "nav-link" %>
          <%= link_to'Log In', new_user_session_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</nav>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
</body>
</html>

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/